export const GET_ROTATIONS = "GET_ROTATIONS"
export const GET_ROTATIONS_SUCCESS = "GET_ROTATIONS_SUCCESS"
export const GET_ROTATIONS_ERROR = "GET_ROTATIONS_ERROR"

export const GET_SPOTS = "GET_SPOTS"
export const GET_SPOTS_SUCCESS = "GET_SPOTS_SUCCESS"
export const GET_SPOTS_ERROR = "GET_SPOTS_ERROR"
export const LOADING = "LOADING"
